"""about_me and last_seen added to User

Revision ID: 501558ccc94d
Revises: 6e3f1d95a8e9
Create Date: 2020-04-07 17:45:43.743002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501558ccc94d'
down_revision = '6e3f1d95a8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
